chain_width = 100
#enum_discrim_align_threshold = 20
fn_args_layout = "Vertical"
#fn_call_width = 40
#imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 256
merge_derives = false
